name: Collect JSON Paths
on:
  push:
    branches:
      - main

jobs:
  collect-json-paths:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.MY_GH_TOKEN }}"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choose the Node.js version you need

      - name: Run Node.js script to collect JSON paths
        run: |
          # node /path/to/your/script.js
          find ./data -type f -name "*.json" > list.txt

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m ":fire: Update JSON paths [skip ci]"
            git push

          else
            echo "No changes to commit."
          fi
